from kedro.pipeline import Pipeline, node
from . import nodes


def create_pipeline(**kwargs):
    return Pipeline(
        [
            node(
                func=nodes.load_raw_posts,
                inputs=dict(
                    mongo_uri="params:MONGO_URI",
                    db_name="params:DB_NAME",
                    raw_collections="params:RAW_COLLECTIONS",
                ),
                outputs="raw_posts",
                name="load_raw_posts_node",
            ),
            node(
                func=nodes.clean_text_node,
                inputs="raw_posts",
                outputs="clean_posts",
                name="clean_text_node",
            ),
            node(
                func=nodes.tokenize_and_lemmatize,
                inputs="clean_posts",
                outputs="tokenized_posts",
                name="tokenize_and_lemmatize_node",
            ),
            node(
                func=nodes.remove_duplicates,
                inputs="tokenized_posts",
                outputs="unique_posts",
                name="remove_duplicates_node",
            ),
            node(
                func=nodes.derive_credibility_labels,
                inputs=["unique_posts", "params:VERIFIED_SOURCES"],
                outputs="credibility_labels",
                name="derive_credibility_labels_node",
            ),
            node(
                func=nodes.vectorize_posts,
                inputs=dict(
                    posts="unique_posts",
                    max_features="params:VECTORIZER_MAX_FEATURES",
                    min_df="params:VECTORIZER_MIN_DF",
                    ngram_range="params:VECTORIZER_NGRAM_RANGE",
                    use_stopwords="params:VECTORIZER_USE_STOPWORDS",
                    custom_stopwords="params:VECTORIZER_CUSTOM_STOPWORDS",
                ),
                outputs=["X_vectors", "labels", "vectorizer"],
                name="vectorize_posts_node",
            ),
            node(
                func=nodes.add_sentiment,
                inputs="unique_posts",
                outputs="posts_with_sentiment",
                name="add_sentiment_node",
            ),
            node(
                func=nodes.add_emotions,
                inputs=[
                    "posts_with_sentiment",
                    "params:EMOTION_USE_TRANSFORMER",
                    "params:EMOTION_MODEL_NAME",
                    "params:EMOTION_TOP_K",
                ],
                outputs="posts_with_emotions",
                name="add_emotions_node",
            ),
            node(
                func=nodes.compute_sentiment_summary,
                inputs="posts_with_emotions",
                outputs=None,
                name="compute_sentiment_summary_node",
            ),
            node(
                func=nodes.compute_emotion_summary,
                inputs="posts_with_emotions",
                outputs=None,
                name="compute_emotion_summary_node",
            ),
            node(
                func=nodes.compute_data_drift_report,
                inputs="posts_with_emotions",
                outputs=None,
                name="compute_data_drift_report_node",
            ),
            node(
                func=nodes.store_cleaned_posts_to_mongo,
                inputs=[
                    "posts_with_emotions",
                    "params:MONGO_URI",
                    "params:DB_NAME",
                    "params:CLEAN_COLLECTION",
                ],
                outputs=None,
                name="store_cleaned_posts_to_mongo_node",
            ),
            node(
                func=nodes.store_vectors_to_postgres,
                inputs=["posts_with_emotions", "X_vectors", "params:POSTGRES_URI"],
                outputs=None,
                name="store_vectors_postgres_node",
            ),
            node(
                func=nodes.train_kmeans,  # clustering + interpretability (top TF-IDF terms per cluster)
                inputs=["X_vectors", "posts_with_emotions", "vectorizer", "params:N_CLUSTERS", "params:CLUSTER_BY"],
                outputs="kmeans_model",
                name="train_kmeans_node",
            ),
            node(
                func=nodes.train_classifier,
                inputs=["X_vectors", "credibility_labels"],
                outputs=["classifier_model", "label_encoder"],
                name="train_classifier_node",
            ), 
            node(
                func=nodes.calibrate_classifier,
                inputs=["X_vectors", "credibility_labels", "classifier_model"],
                outputs="calibrated_classifier",
                name="calibrate_classifier_node",
            ),
            node(
                func=nodes.generate_predictions,
                inputs=[
                    "posts_with_emotions",
                    "X_vectors",
                    "classifier_model",
                    "label_encoder",
                    "calibrated_classifier",
                    "params:ALERT_THRESHOLD",
                ],
                outputs=None,
                name="generate_predictions_node",
            ),
            node(
                func=nodes.build_user_facing_explanations,
                inputs="posts_with_emotions",
                outputs="posts_with_explanations",
                name="build_user_facing_explanations_node",
            ),
            node(
                func=nodes.store_explanations_to_mongo,
                inputs=[
                    "posts_with_explanations",
                    "X_vectors",
                    "classifier_model",
                    "label_encoder",
                    "vectorizer",
                    "params:MONGO_URI",
                    "params:DB_NAME",
                    "params:CLEAN_COLLECTION",
                    "params:EXPLAIN_TOP_N",
                    "calibrated_classifier",
                    "params:ALERT_THRESHOLD",
                ],
                outputs=None,
                name="store_explanations_to_mongo_node",
            ),
            node(
                func=nodes.save_classifier_explanations,
                inputs=["classifier_model", "vectorizer", "label_encoder", "params:EXPLAIN_TOP_N"],
                outputs=None,
                name="save_classifier_explanations_node",
            ),
            node(
                func=nodes.generate_reporting_figures,
                inputs="posts_with_emotions",
                outputs=None,
                name="generate_reporting_figures_node",
            ),
            node(
                func=nodes.train_transformer_model,
                inputs=[
                    "posts_with_emotions",
                    "credibility_labels",
                    "params:ENABLE_TRANSFORMER",
                    "params:TRANSFORMER_MODEL_NAME",
                    "params:TRANSFORMER_OUTPUT_DIR",
                    "params:TRANSFORMER_MAX_LENGTH",
                    "params:TRANSFORMER_EPOCHS",
                    "params:TRANSFORMER_BATCH_SIZE",
                ],
                outputs=None,
                name="train_transformer_model_node",
            ),
            node(
                func=nodes.save_models,
                inputs=["vectorizer", "kmeans_model", "classifier_model", "label_encoder", "calibrated_classifier"],
                outputs=None,
                name="save_models_node",
            ),
        ]
    )
